### ISSUE TITLE
Randomise port used for SSH forwarding

### ISSUE THREAD

**Issue by kgudka** [RichardsonAlex/cheri-scripts#7]
If multiple people use this script on the same host then a hard coded port for SSH will not work. Consider using a user's uid or something that would randomise it.

**Comment by RichardsonAlex** [comment]
I ran into this issue yesterday as well, so I added an option --ssh-forwarding-port or -s that allows you to specify it. I also thought about randomizing it (e.g. using the hash of the username), but what if that random port is already used?

**Comment by kgudka** [comment]
Ah I hadn't realised you had added the option; I think that should be sufficient. Alternatively, you could set the default value to something that is specific to the user and they can then use the -s flag to override it should they need to.

**Comment by kgudka** [comment]
Fixed in f87d46c132e895a12a0d4ec0e87a375a879b3312
